# Generated by Django 2.2.4 on 2019-10-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectpage_is_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='worker',
            new_name='workers',
        ),
    ]
