# Generated by Django 2.2.4 on 2019-10-08 11:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191008_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='project/%Y%m%d'),
        ),
    ]
