# Generated by Django 2.2.4 on 2019-11-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectpage_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='is_homepage',
            field=models.BooleanField(default=False, verbose_name='是否在主页可见'),
        ),
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPage')),
            ],
        ),
    ]
