# Generated by Django 2.2.4 on 2019-11-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191127_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeproject',
            options={'verbose_name': '主页项目', 'verbose_name_plural': '主页项目'},
        ),
    ]
