# Generated by Django 2.2.4 on 2019-09-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, verbose_name='显示排序')),
            ],
            options={
                'verbose_name': '主页内容',
                'verbose_name_plural': '主页内容',
            },
        ),
    ]
