# Generated by Django 2.2.4 on 2019-11-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20191127_2021'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeitem',
            name='roll_project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPage'),
        ),
    ]
