# Generated by Django 2.2.4 on 2019-11-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191127_2050'),
        ('home', '0002_homeitem_roll_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeitem',
            name='roll_project',
        ),
        migrations.AddField(
            model_name='homeitem',
            name='home_project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.HomeProject'),
        ),
        migrations.AddField(
            model_name='homeitem',
            name='roll_rank',
            field=models.PositiveIntegerField(null=True, verbose_name='滚动顺序'),
        ),
        migrations.AlterField(
            model_name='homeitem',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='显示排序'),
        ),
    ]
