# Generated by Django 2.2.4 on 2019-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191127_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeitem',
            options={'ordering': ('rank',), 'verbose_name': '主页内容', 'verbose_name_plural': '主页内容'},
        ),
        migrations.AlterField(
            model_name='homeitem',
            name='rank',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='显示排序'),
        ),
        migrations.AlterField(
            model_name='homeitem',
            name='roll_rank',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='滚动顺序'),
        ),
    ]
